ci: add Vercel deployment for Tilburg repo
nl-design-system/terraform pull request #99
Opened 2024-07-25 16:04 UTC by Robbert

2024-07-25 17:14 UTC, matijs requested changes
Het lijkt me dat het de bedoeling was om `github.tf` te renamen naar `providers.tf` en `terraform.tf` niet te renamen…

2024-07-25 17:23 UTC, matijs commented on tilburg.tf
> +  output_directory = "packages/storybook/dist/"
Misschien ook meteen [dit](https://github.com/nl-design-system/documentatie/blob/main/vercel.json#L8) zodat er voor dependabot PRs niet elke keer Vercel buildjes gedaan worden?

`ignore_command = "[[ $(git log -1 --pretty=%an) == 'dependabot[bot]' ]]"`

2024-07-25 17:36 UTC, Robbert commented on tilburg.tf
> +  output_directory = "packages/storybook/dist/"
geniaal

2024-07-26 07:36 UTC, matijs approved these changes

2024-07-26 07:42 UTC, merged